---
- name: "Create group"
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ user_groups }}"

- name: "Find user's shell if user exists"
  command: "grep {{ username }} /etc/passwd"
  register: grep_result
  changed_when: False
  failed_when: False

- name: "Set current user shell"
  set_fact:
    current_user_shell: "{{ grep_result.stdout.split(':')[-1] }}"
  when: grep_result.rc == 0

- name: "Create user "
  user:
    name: "{{ username }}"
    password: "{{ passwd |password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
    comment: "{{ comment }}"
    groups: "{{ user_groups }}"
    group: "{{ user_groups | first }}"
    generate_ssh_key: "{{ generate_ssh_key }}"
    ssh_key_bits: "{{ ssh_key_bits }}"
    ssh_key_file: "{{ ssh_key_file }}"
    ssh_key_type: "{{ ssh_key_type }}"
    shell: "{{ current_user_shell if current_user_shell is defined else '/bin/bash' }}"
    state: present